-- AlterTable
ALTER TABLE `Route` ADD COLUMN `pickupTime` INTEGER NULL,
    ADD COLUMN `riderLat` VARCHAR(191) NULL,
    ADD COLUMN `riderLng` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'GOING', 'PICKEDUP', 'OTW', 'ARRIVED', 'CANCELED', 'FINISHED') NOT NULL DEFAULT 'PENDING';
